---
version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10

    working_directory: /tmp/repo

    steps:
    - checkout

    # tries to restore dependencies from cache
    - restore_cache:
        keys:
        - v1-dependencies-{{ .Revision }}-{{ .Branch }}
    
    - run: yarn

    # tries to save dependencies to cache
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ .Revision }}-{{ .Branch }}
    
    # run build
    - run: |
        yarn build

    # tries to save distribution to cache
    - save_cache:
        paths:
        - build
        key: v1-dist-{{ .Revision }}-{{ .Branch }}

  docker-build-push:
    docker:
    - image: docker:stable

    working_directory: /tmp/repo

    steps:
    - checkout
    
    - setup_remote_docker

    # tries to restore dependencies from cache
    - restore_cache:
        keys:
        - v1-dependencies-{{ .Revision }}-{{ .Branch }}

    # tries to restore distribution from cache
    - restore_cache:
        keys:
        - v1-dist-{{ .Revision }}-{{ .Branch }}

    # installs jq
    - run: apk add --no-cache jq

    # build and push docker tron-stream image
    - run: |
        export DIST_VERSION=$(cat package.json | jq '.version' -r)
        docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
        docker build . --tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
        if [ "${CIRCLE_BRANCH}" == "master" ]; then
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$DIST_VERSION
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$DIST_VERSION
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
        else
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$DIST_VERSION-$CIRCLE_BRANCH
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$DIST_VERSION-$CIRCLE_BRANCH
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
        fi

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - docker-build-push:
        context: docker-hub-credentials
        requires:
        - build
        filters:
          branches:
            only:
            - development
            - master
